name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  AHKCompileAndRelease:
    name: AHKCompileAndRelease
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: k7jpn.ahk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: k7jpn.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
